export const loremText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nibh justo, bibendum at aliquet quis, dictum dapibus justo. Duis auctor quis est semper sollicitudin. In mattis tempor congue. Mauris sed massa diam. Sed tempor lacus vitae justo sodales auctor. Suspendisse consequat justo turpis, at condimentum tortor bibendum non. Donec vitae libero vel dolor varius feugiat. Quisque in ipsum metus. Quisque ultrices quam in iaculis pharetra. Vivamus egestas velit libero, at faucibus lectus lobortis quis. Aliquam erat volutpat. Sed gravida justo vitae libero rutrum, eu viverra arcu interdum. Vestibulum bibendum tristique est a tincidunt. Aliquam maximus nec elit in tempus. Pellentesque in pulvinar mi. Morbi quis massa sit amet est blandit blandit.

Fusce est libero, elementum ultricies sapien sed, convallis pretium nibh. Donec gravida tristique tristique. Sed a justo nec risus vulputate fermentum. Aliquam at suscipit dolor, quis ullamcorper leo. Nam eu dictum lacus. Donec eget ipsum ex. Sed feugiat tortor ligula, in lobortis turpis porttitor et. Mauris venenatis nisi at blandit gravida. Nulla facilisi. Nulla consectetur pellentesque mattis.

Ut a tempus lacus, quis mollis justo. Vivamus non ex justo. Mauris vitae imperdiet nibh. Integer ultrices quam nunc, in dictum felis sodales non. Sed euismod mauris a est luctus facilisis. In id imperdiet diam. Suspendisse vel pretium neque. Proin molestie tortor non tortor egestas tincidunt. Pellentesque ac ultrices mauris, a bibendum arcu. Phasellus ac quam eu enim condimentum malesuada. Sed lacinia vel libero et porttitor. Sed blandit congue eros ut sodales.

Vestibulum vulputate consequat ex non eleifend. Sed quam odio, vestibulum quis tellus quis, sodales congue metus. Vestibulum mollis, erat sit amet posuere tincidunt, lacus ligula vestibulum augue, ac vestibulum ligula felis ut justo. Mauris finibus sit amet ex vel fringilla. Etiam congue interdum imperdiet. Sed vel molestie nisi, ac dictum metus. Integer tincidunt, dolor sed vulputate aliquet, tellus diam laoreet ante, sit amet pharetra augue lorem id lacus. Quisque mollis ex ut interdum varius. Aenean ut dignissim odio, sed sollicitudin nulla. Morbi tempus tellus non dui aliquam, vitae faucibus justo viverra. Aliquam sed gravida neque. Curabitur facilisis sed turpis sit amet vestibulum. In vitae massa nulla.

Aliquam malesuada, ante ac pellentesque ultricies, neque felis placerat ante, a tempus mi risus facilisis mauris. Etiam scelerisque, massa et molestie congue, odio tellus congue sapien, at porttitor lectus ipsum id leo. Nunc congue sit amet quam ac sollicitudin. Nam ornare euismod tellus, fringilla congue odio rutrum sed. Pellentesque fringilla finibus lorem sed volutpat. Etiam justo velit, pharetra nec venenatis ut, sodales vitae libero. In orci ipsum, lacinia in lorem in, sagittis consequat libero. Proin purus turpis, tempor nec nisi at, ornare aliquam nunc. Fusce et aliquet ipsum. In hac habitasse platea dictumst. Mauris nec ex laoreet, cursus neque vitae, faucibus enim. Nullam efficitur in velit at rhoncus. Mauris posuere nisi vel felis tempus, sit amet gravida nibh viverra. Duis sed tempor neque.`
